### ISSUE TITLE
1695 error code E401

### ISSUE THREAD

**Issue by jnorthrup** [undyingwraith/ipsm#20]
are you dogfooding a discussion on this project?

i thought i would give this project a look but im not sure i grok the need for an npm user account during the build. 

/home/jim/.nvm/versions/node/v16.10.0/bin/node /home/jim/.nvm/versions/node/v16.10.0/lib/node_modules/yarn/bin/yarn.js run install
yarn run v1.22.11
warning ../../package.json: No license field
$ lerna bootstrap
lerna notice cli v4.0.0
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@undyingwraith/ipsm-client'
lerna ERR! npm install stderr:
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ipfs-utils@9.0.2
npm WARN Found: native-fetch@3.0.0
npm WARN node_modules/ipfs-utils/node_modules/native-fetch
npm WARN   native-fetch@"^3.0.0" from ipfs-utils@9.0.2
npm WARN   node_modules/ipfs-utils
npm WARN     ipfs-utils@"^9.0.2" from ipfs-http-client@53.0.1
npm WARN     node_modules/ipfs-http-client
npm WARN     1 more (ipfs-core-utils)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN native-fetch@"^3.0.0" from ipfs-utils@9.0.2
npm WARN node_modules/ipfs-utils
npm WARN   ipfs-utils@"^9.0.2" from ipfs-http-client@53.0.1
npm WARN   node_modules/ipfs-http-client
npm WARN   1 more (ipfs-core-utils)
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jim/.npm/_logs/2021-10-02T18_42_31_723Z-debug.log
lerna ERR! npm install exited 1 in '@undyingwraith/ipsm-client'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
attached

[2021-10-02T18_42_31_723Z-debug.log](https://github.com/undyingwraith/ipsm/files/7272026/2021-10-02T18_42_31_723Z-debug.log)

**Comment by undyingwraith** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#authenticating-to-github-packages

Its not on the npm registry but the github registry. Which sadly requires you to log in.

**Comment by jnorthrup** [comment]
file that one in the barriers to entry column..
